# Generated by Django 4.2.4 on 2023-10-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mychats',
            name='chats',
            field=models.JSONField(default=dict),
        ),
    ]
